---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/lev-ci
  commands:
  - echo "$${DOCKER_PASSWORD}" | docker login -u "ukhomeofficedigital+design_system" --password-stdin "quay.io"
  - npm install -g pnpm
  - cd 'apps/docs'
  - make deploy kubectl="kubectl --insecure-skip-tls-verify --server=$${KUBE_SERVER} --namespace=$${KUBE_NAMESPACE} --token=$${KUBE_TOKEN}"
  environment:
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    KUBE_CONTAINER:
      from_secret: KUBE_CONTAINER
    KUBE_DEPLOYMENT:
      from_secret: KUBE_DEPLOYMENT
    KUBE_NAMESPACE:
      from_secret: KUBE_NAMESPACE
    KUBE_SERVER:
      from_secret: KUBE_SERVER
    KUBE_TOKEN:
      from_secret: KUBE_TOKEN
    NODE_OPTIONS: --max_old_space_size=4096
  when:
    branch:
    - master
    event:
    - push
  resources:
    requests:
      cpu: 500
      memory: 4GiB
    limits:
      cpu: 4000
      memory: 5GiB

- name: notify_slack_success
  pull: if-not-exists
  image: plugins/slack:1.0
  settings:
    channel: ho-design-system
    template: "*Deployed {{repo.name}}* - <{{build.link}}|#{{build.number}}>\n"
    username: Drone
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  when:
    branch:
    - master
    event:
    - push
    status:
    - success

- name: notify_slack_failure
  pull: if-not-exists
  image: plugins/slack
  settings:
    channel: ho-design-system
    template: "*Failed to deploy {{repo.name}}*\nAuthor: {{build.author}}\nDuration: {{since job.started}} Job: <{{build.link}}|#{{build.number}}>\nCommit: {{build.commit}}\n"
    username: Drone
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  when:
    branch:
    - master
    event:
    - push
    status:
    - failure

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
